In [1]:
import pandas as pd
import numpy as np

print("Pandas version:", pd.__version__)
print("NumPy version:", np.__version__)

Pandas version: 2.3.3
NumPy version: 2.3.5

In [2]:
import pandas as pd
import numpy as np

# ============================================================
# 1. SETTINGS
# ============================================================

np.random.seed(42)

total_records = 20000
original_records = 19000
duplicate_records = 1000


# ============================================================
# 2. MASTER DATA
# ============================================================

first_names = [
    'Rahul', 'Amit', 'Rohit', 'Vikas', 'Suresh',
    'Ankit', 'Arjun', 'Karan', 'Vivek', 'Raj',
    'Priya', 'Neha', 'Pooja', 'Anjali', 'Sneha',
    'Kavita', 'Riya', 'Shreya', 'Swati', 'Nisha',
    'Akash', 'Manish', 'Abhishek', 'Deepak', 'Sanjay'
]

last_names = [
    'Sharma', 'Kumar', 'Patel', 'Singh', 'Das',
    'Panda', 'Reddy', 'Rao', 'Mishra', 'Verma',
    'Gupta', 'Mehta', 'Jain', 'Nayak', 'Sahu',
    'Behera', 'Mohanty', 'Dutta', 'Yadav', 'Pradhan'
]

products = [
    'Laptop',
    'Smartphone',
    'Tablet',
    'Headphones',
    'Smart Watch',
    'Keyboard',
    'Mouse',
    'Monitor',
    'Printer',
    'Camera',
    'Power Bank',
    'Earbuds',
    'Bluetooth Speaker',
    'Gaming Chair',
    'Backpack',
    'USB Cable',
    'External Hard Drive',
    'SSD',
    'Webcam',
    'Router'
]

categories = [
    'Electronics',
    'Computer Accessories',
    'Furniture',
    'Bags',
    'Networking'
]

cities = [
    'Hyderabad',
    'Bangalore',
    'Mumbai',
    'Delhi',
    'Pune',
    'Chennai',
    'Kolkata',
    'Bhubaneswar',
    'Cuttack',
    'Visakhapatnam',
    'Ahmedabad',
    'Jaipur',
    'Lucknow',
    'Bhopal',
    'Patna'
]

states = [
    'Telangana',
    'Karnataka',
    'Maharashtra',
    'Delhi',
    'Maharashtra',
    'Tamil Nadu',
    'West Bengal',
    'Odisha',
    'Odisha',
    'Andhra Pradesh',
    'Gujarat',
    'Rajasthan',
    'Uttar Pradesh',
    'Madhya Pradesh',
    'Bihar'
]

payment_methods = [
    'UPI',
    'Credit Card',
    'Debit Card',
    'Cash on Delivery',
    'Net Banking',
    'Wallet'
]

order_status = [
    'Delivered',
    'Delivered',
    'Delivered',
    'Delivered',
    'Cancelled',
    'Returned',
    'Pending'
]


# ============================================================
# 3. GENERATE 19,000 ORIGINAL RECORDS
# ============================================================

data = []

for i in range(original_records):

    first_name = np.random.choice(first_names)
    last_name = np.random.choice(last_names)

    customer_name = first_name + ' ' + last_name

    order_id = f'ORD{100001 + i}'

    customer_id = f'CUST{10001 + i}'

    gender = np.random.choice([
        'Male',
        'Female'
    ])

    age = np.random.randint(
        18,
        66
    )

    product = np.random.choice(
        products
    )

    category = np.random.choice(
        categories
    )

    city_index = np.random.randint(
        0,
        len(cities)
    )

    city = cities[city_index]

    state = states[city_index]

    quantity = np.random.randint(
        1,
        6
    )

    unit_price = np.random.randint(
        500,
        100000
    )

    discount = np.random.choice([
        0,
        5,
        10,
        15,
        20,
        25,
        30
    ])

    sales = (
        quantity *
        unit_price *
        (1 - discount / 100)
    )

    sales = round(
        sales,
        2
    )

    profit = round(
        sales * np.random.uniform(
            0.05,
            0.25
        ),
        2
    )

    order_date = pd.Timestamp(
        np.random.choice(
            pd.date_range(
                '2022-01-01',
                '2025-12-31'
            )
        )
    )

    payment = np.random.choice(
        payment_methods
    )

    status = np.random.choice(
        order_status
    )

    data.append([
        order_id,
        order_date,
        customer_id,
        customer_name,
        gender,
        age,
        product,
        category,
        quantity,
        unit_price,
        discount,
        sales,
        profit,
        payment,
        city,
        state,
        status
    ])


# ============================================================
# 4. CREATE DATAFRAME
# ============================================================

columns = [
    'Order_ID',
    'Order_Date',
    'Customer_ID',
    'Customer_Name',
    'Gender',
    'Age',
    'Product',
    'Category',
    'Quantity',
    'Unit_Price',
    'Discount_Percentage',
    'Sales',
    'Profit',
    'Payment_Method',
    'City',
    'State',
    'Order_Status'
]

df = pd.DataFrame(
    data,
    columns=columns
)


# ============================================================
# 5. ADD MISSING VALUES INTENTIONALLY
# ============================================================

# Customer Name - 150 missing
index = np.random.choice(
    df.index,
    150,
    replace=False
)

df.loc[index, 'Customer_Name'] = np.nan


# Gender - 100 missing
index = np.random.choice(
    df.index,
    100,
    replace=False
)

df.loc[index, 'Gender'] = np.nan


# Age - 120 missing
index = np.random.choice(
    df.index,
    120,
    replace=False
)

df.loc[index, 'Age'] = np.nan


# Product - 100 missing
index = np.random.choice(
    df.index,
    100,
    replace=False
)

df.loc[index, 'Product'] = np.nan


# Category - 100 missing
index = np.random.choice(
    df.index,
    100,
    replace=False
)

df.loc[index, 'Category'] = np.nan


# Quantity - 100 missing
index = np.random.choice(
    df.index,
    100,
    replace=False
)

df.loc[index, 'Quantity'] = np.nan


# Unit Price - 120 missing
index = np.random.choice(
    df.index,
    120,
    replace=False
)

df.loc[index, 'Unit_Price'] = np.nan


# Discount - 100 missing
index = np.random.choice(
    df.index,
    100,
    replace=False
)

df.loc[index, 'Discount_Percentage'] = np.nan


# Sales - 100 missing
index = np.random.choice(
    df.index,
    100,
    replace=False
)

df.loc[index, 'Sales'] = np.nan


# Profit - 120 missing
index = np.random.choice(
    df.index,
    120,
    replace=False
)

df.loc[index, 'Profit'] = np.nan


# Payment Method - 100 missing
index = np.random.choice(
    df.index,
    100,
    replace=False
)

df.loc[index, 'Payment_Method'] = np.nan


# City - 100 missing
index = np.random.choice(
    df.index,
    100,
    replace=False
)

df.loc[index, 'City'] = np.nan


# State - 100 missing
index = np.random.choice(
    df.index,
    100,
    replace=False
)

df.loc[index, 'State'] = np.nan


# Order Status - 100 missing
index = np.random.choice(
    df.index,
    100,
    replace=False
)

df.loc[index, 'Order_Status'] = np.nan


# ============================================================
# 6. ADD INCONSISTENT DATA INTENTIONALLY
# ============================================================

# Category inconsistencies

index = np.random.choice(
    df.dropna(subset=['Category']).index,
    300,
    replace=False
)

category_changes = [
    'electronics',
    'ELECTRONICS',
    ' Electronics ',
    'computer accessories',
    'COMPUTER ACCESSORIES',
    ' Computer Accessories ',
    'furniture',
    'FURNITURE',
    ' Furniture ',
    'bags',
    'BAGS',
    ' Bags '
]

for i in index:
    df.loc[i, 'Category'] = np.random.choice(
        category_changes
    )


# City inconsistencies

index = np.random.choice(
    df.dropna(subset=['City']).index,
    300,
    replace=False
)

city_changes = [
    'hyderabad',
    'HYDERABAD',
    ' Hyderabad ',
    'bangalore',
    'BANGALORE',
    ' Bangalore ',
    'mumbai',
    'MUMBAI',
    ' Mumbai ',
    'delhi',
    'DELHI',
    ' Delhi ',
    'pune',
    'PUNE',
    ' Pune '
]

for i in index:
    df.loc[i, 'City'] = np.random.choice(
        city_changes
    )


# ============================================================
# 7. ADD INVALID VALUES INTENTIONALLY
# ============================================================

# Invalid Quantity

index = np.random.choice(
    df.index,
    100,
    replace=False
)

df.loc[index, 'Quantity'] = np.random.choice([
    -5,
    -1,
    0,
    100,
    500
], 100)


# Invalid Discount

index = np.random.choice(
    df.index,
    100,
    replace=False
)

df.loc[index, 'Discount_Percentage'] = np.random.choice([
    -10,
    -5,
    105,
    150
], 100)


# Invalid Sales / Outliers

index = np.random.choice(
    df.index,
    50,
    replace=False
)

df.loc[index, 'Sales'] = np.random.choice([
    -500,
    -1000,
    500000,
    1000000
], 50)


# ============================================================
# 8. ADD 1,000 DUPLICATE RECORDS INTENTIONALLY
# ============================================================

duplicate_data = df.sample(
    n=duplicate_records,
    random_state=42
)

df = pd.concat(
    [
        df,
        duplicate_data
    ],
    ignore_index=True
)


# ============================================================
# 9. SHUFFLE THE DATA
# ============================================================

df = df.sample(
    frac=1,
    random_state=42
).reset_index(drop=True)


# ============================================================
# 10. CHECK EXACT NUMBER OF RECORDS
# ============================================================

print("Number of records:", len(df))

print("Number of columns:", len(df.columns))


# ============================================================
# 11. DISPLAY DATAFRAME
# ============================================================

df.head()

Number of records: 20000
Number of columns: 17

,Order_ID,Order_Date,Customer_ID,Customer_Name,Gender,Age,Product,Category,Quantity,Unit_Price,Discount_Percentage,Sales,Profit,Payment_Method,City,State,Order_Status
0,ORD110651,2024-06-06,CUST20651,Priya Jain,Female,58.0,Keyboard,Networking,5.0,29379.0,10.0,132205.50,14631.18,Wallet,Kolkata,West Bengal,Delivered
1,ORD102042,2022-08-31,CUST12042,Ankit Dutta,Male,28.0,Printer,Furniture,2.0,67778.0,0.0,135556.00,31852.25,Wallet,Bangalore,Karnataka,Delivered
2,ORD108669,2024-11-29,CUST18669,NaN,Male,62.0,Monitor,Computer Accessories,1.0,13662.0,20.0,10929.60,2218.22,UPI,Delhi,Delhi,Delivered
3,ORD101115,2025-08-22,CUST11115,Sanjay Mohanty,Female,45.0,SSD,Furniture,5.0,33235.0,25.0,124631.25,27319.26,Credit Card,Bangalore,Karnataka,Delivered
4,ORD113903,2025-05-25,CUST23903,Rohit Pradhan,Male,57.0,Smartphone,Networking,5.0,8863.0,15.0,37667.75,2186.07,Cash on Delivery,Chennai,Tamil Nadu,Returned

In [3]:
df.shape

(20000, 17)

In [4]:
df.to_csv(r"C:\Users\Rashmi Ranjan Panda\OneDrive\Desktop\Ecommerce-Sales-Analytics\notebooks\ecommerce_sales_raw.csv")

Data Loading And Inspection

In [5]:
df.head()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Gender,Age,Product,Category,Quantity,Unit_Price,Discount_Percentage,Sales,Profit,Payment_Method,City,State,Order_Status
0,ORD110651,2024-06-06,CUST20651,Priya Jain,Female,58.0,Keyboard,Networking,5.0,29379.0,10.0,132205.50,14631.18,Wallet,Kolkata,West Bengal,Delivered
1,ORD102042,2022-08-31,CUST12042,Ankit Dutta,Male,28.0,Printer,Furniture,2.0,67778.0,0.0,135556.00,31852.25,Wallet,Bangalore,Karnataka,Delivered
2,ORD108669,2024-11-29,CUST18669,NaN,Male,62.0,Monitor,Computer Accessories,1.0,13662.0,20.0,10929.60,2218.22,UPI,Delhi,Delhi,Delivered
3,ORD101115,2025-08-22,CUST11115,Sanjay Mohanty,Female,45.0,SSD,Furniture,5.0,33235.0,25.0,124631.25,27319.26,Credit Card,Bangalore,Karnataka,Delivered
4,ORD113903,2025-05-25,CUST23903,Rohit Pradhan,Male,57.0,Smartphone,Networking,5.0,8863.0,15.0,37667.75,2186.07,Cash on Delivery,Chennai,Tamil Nadu,Returned

In [6]:
# Check the shape.
df.shape

(20000, 17)

In [7]:
# Check the columns
df.columns

Index(['Order_ID', 'Order_Date', 'Customer_ID', 'Customer_Name', 'Gender',
       'Age', 'Product', 'Category', 'Quantity', 'Unit_Price',
       'Discount_Percentage', 'Sales', 'Profit', 'Payment_Method', 'City',
       'State', 'Order_Status'],
      dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Order_ID             20000 non-null  object
 1   Order_Date           20000 non-null  datetime64[ns]
 2   Customer_ID          20000 non-null  object
 3   Customer_Name        19838 non-null  object
 4   Gender               19896 non-null  object
 5   Age                  19875 non-null  float64
 6   Product              19894 non-null  object
 7   Category             19895 non-null  object
 8   Quantity             19892 non-null  float64
 9   Unit_Price           19874 non-null  float64
 10  Discount_Percentage  19893 non-null  float64
 11  Sales                19895 non-null  float64
 12  Profit               19873 non-null  float64
 13  Payment_Method       19894 non-null  object
 14  City                 19896 non-null  object
 15  State                19890 non-null  object
 16  Order_Status         19895 non-null  object
dtypes: datetime64[ns](1), float64(6), object(10)
memory usage: 2.6+ MB

In [9]:
df.describe()

,Order_Date,Age,Quantity,Unit_Price,Discount_Percentage,Sales,Profit
count,20000,19875.000000,19892.000000,19874.000000,19893.000000,19895.000000,19873.000000
mean,2024-01-03 19:17:24.000000256,41.600050,3.471144,50133.168562,15.185492,128860.331345,19270.322241
min,2022-01-01 00:00:00,18.000000,-5.000000,501.000000,-10.000000,-1000.000000,35.270000
25%,2023-01-01 00:00:00,30.000000,2.000000,24924.500000,5.000000,46112.500000,5855.920000
50%,2024-01-09 12:00:00,41.000000,3.000000,50299.500000,15.000000,98467.200000,13554.670000
75%,2025-01-05 00:00:00,54.000000,4.000000,75111.000000,25.000000,189966.700000,27202.200000
max,2025-12-31 00:00:00,65.000000,500.000000,99998.000000,150.000000,1000000.000000,117234.610000
std,NaN,13.874268,14.425984,28777.947200,11.558752,105620.721515,18100.583470

CHECKING THE MISSING VALUES

In [10]:
df.isnull().sum()

Order_ID                 0
Order_Date               0
Customer_ID              0
Customer_Name          162
Gender                 104
Age                    125
Product                106
Category               105
Quantity               108
Unit_Price             126
Discount_Percentage    107
Sales                  105
Profit                 127
Payment_Method         106
City                   104
State                  110
Order_Status           105
dtype: int64

CHECKING THE DUPLICATE RECORDES

In [11]:
df.duplicated().sum()

np.int64(1000)

In [12]:
df.shape

(20000, 17)

CALCULATE THE MISSING VALUE PERCENTAGE

In [13]:
missing_count=df.isnull().sum()
missing_percentage=missing_count/len(df)*100
missing_data=pd.DataFrame({
    'Missing_Count':missing_count,
    'Missing_Percentage':missing_percentage
})
missing_data

                     Missing_Count  Missing_Percentage
Order_ID                         0               0.000
Order_Date                       0               0.000
Customer_ID                      0               0.000
Customer_Name                  162               0.810
Gender                         104               0.520
Age                            125               0.625
Product                        106               0.530
Category                       105               0.525
Quantity                       108               0.540
Unit_Price                     126               0.630
Discount_Percentage            107               0.535
Sales                          105               0.525
Profit                         127               0.635
Payment_Method                 106               0.530
City                           104               0.520
State                          110               0.550
Order_Status                   105               0.525

 # Find rows containing missing values

In [14]:
df[df.isnull().any(axis=1)].head()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Gender,Age,Product,Category,Quantity,Unit_Price,Discount_Percentage,Sales,Profit,Payment_Method,City,State,Order_Status
2,ORD108669,2024-11-29,CUST18669,NaN,Male,62.0,Monitor,Computer Accessories,1.0,13662.0,20.0,10929.60,2218.22,UPI,Delhi,Delhi,Delivered
6,ORD111073,2024-10-02,CUST21073,Suresh Mehta,Male,46.0,Camera,Furniture,4.0,46818.0,30.0,131090.40,19267.63,Credit Card,Bhubaneswar,Odisha,NaN
18,ORD108095,2022-01-23,CUST18095,Nisha Kumar,Female,NaN,Smart Watch,Electronics,5.0,58439.0,5.0,277585.25,55705.41,UPI,Visakhapatnam,Andhra Pradesh,Returned
24,ORD109120,2023-05-01,CUST19120,Vikas Pradhan,Female,45.0,Backpack,Computer Accessories,5.0,77587.0,30.0,271554.50,NaN,Debit Card,Bangalore,Karnataka,Delivered
83,ORD118831,2024-02-28,CUST28831,Arjun Sharma,Male,57.0,Printer,Electronics,4.0,62289.0,NaN,211782.60,22557.83,Credit Card,Pune,Maharashtra,Delivered

## Find columns with missing values

In [15]:
df.columns[df.isnull().any(axis=0)]

Index(['Customer_Name', 'Gender', 'Age', 'Product', 'Category', 'Quantity',
       'Unit_Price', 'Discount_Percentage', 'Sales', 'Profit',
       'Payment_Method', 'City', 'State', 'Order_Status'],
      dtype='object')

### Visual check

In [16]:
# Here i am try to collect the missing data and  remove the other data recordes.
# Before we crreated a dataframe named missing_data from that dataframe we only select the missing values recordes.
missing_data=missing_data[missing_data['Missing_Count']>0]
missing_data.sort_values(by='Missing_Count',ascending=False)

                     Missing_Count  Missing_Percentage
Customer_Name                  162               0.810
Profit                         127               0.635
Unit_Price                     126               0.630
Age                            125               0.625
State                          110               0.550
Quantity                       108               0.540
Discount_Percentage            107               0.535
Product                        106               0.530
Payment_Method                 106               0.530
Category                       105               0.525
Sales                          105               0.525
Order_Status                   105               0.525
Gender                         104               0.520
City                           104               0.520

# Analyze Duplicate Records

## Count duplicate rows

In [17]:
# Here we count the total numbers of duplicated rows or recordes.
df.duplicated().sum()

np.int64(1000)

### Display the duplicate rows

In [18]:
# For display the duplicate recordes we can use.
df[df.duplicated()].head(10)

,Order_ID,Order_Date,Customer_ID,Customer_Name,Gender,Age,Product,Category,Quantity,Unit_Price,Discount_Percentage,Sales,Profit,Payment_Method,City,State,Order_Status
610,ORD102268,2025-08-22,CUST12268,Rohit Mohanty,Male,30.0,Camera,Networking,4.0,98499.0,-10.0,374296.2,87453.60,UPI,Jaipur,Rajasthan,Delivered
644,ORD116616,2023-08-24,CUST26616,Vikas Rao,Female,37.0,Monitor,Bags,3.0,26823.0,0.0,80469.0,17132.71,UPI,Bhubaneswar,Odisha,Returned
670,ORD114284,2025-11-29,CUST24284,Suresh Dutta,Male,65.0,Backpack,Electronics,2.0,12006.0,25.0,18009.0,2389.99,Net Banking,Chennai,Tamil Nadu,Returned
794,ORD107880,2025-11-24,CUST17880,Manish Singh,Male,39.0,Headphones,Networking,4.0,3230.0,20.0,10336.0,2571.73,Credit Card,Bhubaneswar,Odisha,Delivered
882,ORD104059,2022-03-04,CUST14059,Suresh Patel,Female,35.0,Earbuds,Computer Accessories,4.0,8807.0,15.0,29943.8,2189.02,Cash on Delivery,Visakhapatnam,Andhra Pradesh,Delivered
925,ORD107376,2024-11-26,CUST17376,Swati Mohanty,Male,30.0,Printer,Bags,5.0,20264.0,20.0,81056.0,15506.53,Wallet,Hyderabad,Telangana,Delivered
971,ORD102130,2024-08-11,CUST12130,Nisha Verma,Female,64.0,Tablet,Computer Accessories,5.0,59563.0,30.0,208470.5,44677.55,Debit Card,Chennai,Tamil Nadu,Pending
1028,ORD101035,2024-04-28,CUST11035,Neha Mishra,Male,63.0,Router,Electronics,NaN,93444.0,0.0,186888.0,18360.13,Credit Card,Patna,Bihar,Delivered
1038,ORD104392,2025-01-25,CUST14392,Deepak Yadav,Male,29.0,Printer,Electronics,3.0,66680.0,5.0,190038.0,43291.06,Debit Card,Lucknow,NaN,Delivered
1296,ORD104451,2025-05-09,CUST14451,Riya Nayak,Male,54.0,Smartphone,Furniture,1.0,61955.0,0.0,61955.0,12526.68,Net Banking,Bangalore,Karnataka,Delivered

### Check duplicates including the first occurrence

In [19]:
# Here we can use the keep parameter to keep the first record as the original one and remaning are dupliccates.
df.duplicated(keep='first').head()

0    False
1    False
2    False
3    False
4    False
dtype: bool

### Check duplicate Order IDs

In [20]:
# WE can check the duplicated order ID's by,
df['Order_ID'].duplicated().sum()

np.int64(1000)

In [21]:
# Display The duplicated Order_ID's
df[df['Order_ID'].duplicated(keep='first')].sort_values(by='Order_ID')

,Order_ID,Order_Date,Customer_ID,Customer_Name,Gender,Age,Product,Category,Quantity,Unit_Price,Discount_Percentage,Sales,Profit,Payment_Method,City,State,Order_Status
18772,ORD100007,2023-05-08,CUST10007,Karan Behera,Male,35.0,Backpack,Networking,2.0,64204.0,15.0,109146.8,18708.51,UPI,Bhubaneswar,Odisha,Cancelled
17710,ORD100036,2022-10-12,CUST10036,Rahul Sharma,Male,60.0,Smart Watch,Bags,1.0,38804.0,5.0,36863.8,3367.02,Net Banking,Mumbai,Maharashtra,Delivered
3493,ORD100043,2025-06-07,CUST10043,Rohit Gupta,Male,35.0,Backpack,Bags,2.0,83373.0,NaN,141734.1,31659.68,Wallet,Cuttack,Odisha,Cancelled
15223,ORD100058,2024-09-10,CUST10058,Shreya Kumar,Female,47.0,Backpack,Furniture,2.0,83751.0,0.0,167502.0,25593.95,Cash on Delivery,Mumbai,Maharashtra,Returned
5134,ORD100060,2025-10-29,CUST10060,Ankit Kumar,Male,60.0,Power Bank,Furniture,1.0,24714.0,30.0,17299.8,2888.26,Cash on Delivery,Mumbai,Maharashtra,Delivered
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16247,ORD118856,2022-08-10,CUST28856,Manish Rao,Male,18.0,SSD,Furniture,3.0,77843.0,20.0,186823.2,38038.75,Cash on Delivery,Bhubaneswar,Odisha,Pending
3695,ORD118866,2022-06-14,CUST28866,Arjun Singh,Female,35.0,Keyboard,Computer Accessories,3.0,21386.0,15.0,54534.3,4896.91,Wallet,Cuttack,Odisha,Delivered
15015,ORD118925,2025-11-17,CUST28925,Anjali Sahu,Female,34.0,SSD,Bags,4.0,89136.0,0.0,356544.0,80887.61,Net Banking,Mumbai,Maharashtra,Delivered
16100,ORD118976,2024-01-16,CUST28976,Shreya Nayak,Male,40.0,External Hard Drive,Computer Accessories,3.0,1546.0,25.0,3478.5,232.90,Wallet,Lucknow,Uttar Pradesh,Delivered
8260,ORD118999,2025-01-06,CUST28999,Priya Behera,Female,30.0,Bluetooth Speaker,Computer Accessories,4.0,46884.0,20.0,150028.8,20361.45,Credit Card,Chennai,Tamil Nadu,Pending

## Check Data Types

In [22]:
df.dtypes

Order_ID                       object
Order_Date             datetime64[ns]
Customer_ID                    object
Customer_Name                  object
Gender                         object
Age                           float64
Product                        object
Category                       object
Quantity                      float64
Unit_Price                    float64
Discount_Percentage           float64
Sales                         float64
Profit                        float64
Payment_Method                 object
City                           object
State                          object
Order_Status                   object
dtype: object

In [23]:
# Check The Numerical columns in the dataframe.
df.select_dtypes(include='number').columns

Index(['Age', 'Quantity', 'Unit_Price', 'Discount_Percentage', 'Sales',
       'Profit'],
      dtype='object')

## Find The Unique Values In The Categorical COlumn

In [24]:
# 1st i have to know all the categorical column in the dataframe.
categorical_columns=df.select_dtypes(include=['object']).columns
categorical_columns

Index(['Order_ID', 'Customer_ID', 'Customer_Name', 'Gender', 'Product',
       'Category', 'Payment_Method', 'City', 'State', 'Order_Status'],
      dtype='object')

In [25]:
# Find the unique values in the Order_ID column.
df['Order_ID'].unique()

array(['ORD110651', 'ORD102042', 'ORD108669', ..., 'ORD105391',
       'ORD100861', 'ORD115796'], shape=(19000,), dtype=object)

In [26]:
df['Order_ID'].duplicated(keep='first').sum()

np.int64(1000)

In [27]:
# Find The unique values in the column named Gender.
print(df['Gender'].unique())

[np.str_('Female') np.str_('Male') nan]

In [28]:
df['Product'].unique()

array([np.str_('Keyboard'), np.str_('Printer'), np.str_('Monitor'),
       np.str_('SSD'), np.str_('Smartphone'), np.str_('Mouse'),
       np.str_('Camera'), np.str_('Gaming Chair'), np.str_('Headphones'),
       np.str_('Bluetooth Speaker'), np.str_('Webcam'),
       np.str_('Smart Watch'), np.str_('USB Cable'), np.str_('Backpack'),
       np.str_('Tablet'), np.str_('Power Bank'), np.str_('Router'),
       np.str_('External Hard Drive'), np.str_('Earbuds'),
       np.str_('Laptop'), nan], dtype=object)

In [29]:
df['Category'].unique()

array([np.str_('Networking'), np.str_('Furniture'),
       np.str_('Computer Accessories'), np.str_('Electronics'),
       np.str_('Bags'), np.str_('FURNITURE'), np.str_('furniture'),
       np.str_('ELECTRONICS'), np.str_('COMPUTER ACCESSORIES'),
       np.str_(' Computer Accessories '), nan, np.str_(' Bags '),
       np.str_('bags'), np.str_('electronics'), np.str_(' Furniture '),
       np.str_('computer accessories'), np.str_(' Electronics '),
       np.str_('BAGS')], dtype=object)

In [30]:
df['Payment_Method'].unique()

array([np.str_('Wallet'), np.str_('UPI'), np.str_('Credit Card'),
       np.str_('Cash on Delivery'), np.str_('Debit Card'),
       np.str_('Net Banking'), nan], dtype=object)

In [31]:
df['City'].unique()

array(['Kolkata', 'Bangalore', 'Delhi', 'Chennai', 'Mumbai',
       'Bhubaneswar', 'Pune', 'Cuttack', 'Visakhapatnam', 'Ahmedabad',
       'Lucknow', 'Bhopal', 'Jaipur', 'Patna', 'Hyderabad',
       np.str_('MUMBAI'), np.str_('BANGALORE'), nan, np.str_('hyderabad'),
       np.str_(' Pune '), np.str_('mumbai'), np.str_(' Hyderabad '),
       np.str_('DELHI'), np.str_('delhi'), np.str_(' Delhi '),
       np.str_('PUNE'), np.str_(' Mumbai '), np.str_('pune'),
       np.str_(' Bangalore '), np.str_('HYDERABAD'), np.str_('bangalore')],
      dtype=object)

In [32]:
df['State'].unique()

array(['West Bengal', 'Karnataka', 'Delhi', 'Tamil Nadu', 'Maharashtra',
       'Odisha', 'Andhra Pradesh', 'Gujarat', 'Uttar Pradesh',
       'Madhya Pradesh', 'Rajasthan', 'Bihar', 'Telangana', nan],
      dtype=object)

In [33]:
df['Order_Status'].unique()

array([np.str_('Delivered'), np.str_('Returned'), nan, np.str_('Pending'),
       np.str_('Cancelled')], dtype=object)

In [34]:
df['Order_ID'].value_counts(dropna=False)

Order_ID
ORD117694    2
ORD104198    2
ORD102248    2
ORD105271    2
ORD111072    2
            ..
ORD118535    1
ORD112446    1
ORD103287    1
ORD111399    1
ORD115796    1
Name: count, Length: 19000, dtype: int64

In [35]:
df['Gender'].value_counts(dropna=False)

Gender
Female    10007
Male       9889
NaN         104
Name: count, dtype: int64

In [36]:
df['Product'].value_counts(dropna=False)

Product
Smart Watch            1056
Webcam                 1037
USB Cable              1033
External Hard Drive    1031
Gaming Chair           1014
Monitor                1005
Bluetooth Speaker      1004
SSD                    1004
Power Bank             1002
Keyboard                993
Smartphone              992
Printer                 991
Earbuds                 989
Router                  984
Headphones              982
Tablet                  972
Laptop                  959
Camera                  956
Backpack                946
Mouse                   944
NaN                     106
Name: count, dtype: int64

In [37]:
df['Category'].value_counts(dropna=False)

Category
Networking                3978
Furniture                 3962
Electronics               3935
Bags                      3896
Computer Accessories      3810
NaN                        105
 Bags                       33
computer accessories        32
COMPUTER ACCESSORIES        31
FURNITURE                   30
 Electronics                28
BAGS                        28
bags                        24
furniture                   24
electronics                 23
 Computer Accessories       23
ELECTRONICS                 22
 Furniture                  16
Name: count, dtype: int64

In [38]:
df['Payment_Method'].value_counts(dropna=False)

Payment_Method
Net Banking         3375
Credit Card         3362
Wallet              3312
Cash on Delivery    3312
UPI                 3285
Debit Card          3248
NaN                  106
Name: count, dtype: int64

In [39]:
df['City'].value_counts(dropna=False)

City
Delhi            1353
Visakhapatnam    1350
Kolkata          1348
Bhubaneswar      1348
Cuttack          1330
Chennai          1327
Hyderabad        1322
Lucknow          1304
Bangalore        1302
Pune             1298
Patna            1296
Jaipur           1280
Bhopal           1248
Ahmedabad        1237
Mumbai           1237
NaN               104
DELHI              29
delhi              26
 Delhi             25
HYDERABAD          24
 Mumbai            24
BANGALORE          23
 Hyderabad         23
pune               22
hyderabad          21
 Pune              20
PUNE               18
mumbai             16
MUMBAI             15
 Bangalore         15
bangalore          15
Name: count, dtype: int64

In [40]:
df['Order_Status'].value_counts(dropna=False)

Order_Status
Delivered    11296
Pending       2873
Cancelled     2865
Returned      2861
NaN            105
Name: count, dtype: int64

In [41]:
df['State'].value_counts(dropna=False)

State
Odisha            2711
Maharashtra       2581
Delhi             1366
Andhra Pradesh    1366
West Bengal       1364
Telangana         1350
Tamil Nadu        1348
Karnataka         1333
Uttar Pradesh     1326
Bihar             1320
Rajasthan         1301
Madhya Pradesh    1273
Gujarat           1251
NaN                110
Name: count, dtype: int64

### Checking The Missing Values In the entier Dtaframe

In [42]:
missing_value_count=df.isnull().sum()
missing_value_count

Order_ID                 0
Order_Date               0
Customer_ID              0
Customer_Name          162
Gender                 104
Age                    125
Product                106
Category               105
Quantity               108
Unit_Price             126
Discount_Percentage    107
Sales                  105
Profit                 127
Payment_Method         106
City                   104
State                  110
Order_Status           105
dtype: int64

### Calculate the missing percentage

In [43]:
missing_percentage=(missing_value_count/len(df))*100
missing_percentage

Order_ID               0.000
Order_Date             0.000
Customer_ID            0.000
Customer_Name          0.810
Gender                 0.520
Age                    0.625
Product                0.530
Category               0.525
Quantity               0.540
Unit_Price             0.630
Discount_Percentage    0.535
Sales                  0.525
Profit                 0.635
Payment_Method         0.530
City                   0.520
State                  0.550
Order_Status           0.525
dtype: float64

### combined missing-value summary

In [44]:
missing_value_summary=pd.DataFrame({
    'Missing Value Count':missing_value_count,
    'Missing Value Percentage':missing_percentage
})
missing_value_summary

                     Missing Value Count  Missing Value Percentage
Order_ID                               0                     0.000
Order_Date                             0                     0.000
Customer_ID                            0                     0.000
Customer_Name                        162                     0.810
Gender                               104                     0.520
Age                                  125                     0.625
Product                              106                     0.530
Category                             105                     0.525
Quantity                             108                     0.540
Unit_Price                           126                     0.630
Discount_Percentage                  107                     0.535
Sales                                105                     0.525
Profit                               127                     0.635
Payment_Method                       106                     0.530
City                                 104                     0.520
State                                110                     0.550
Order_Status                         105                     0.525

### Sort The missing value by number of count

In [45]:
missing_value_summary=missing_value_summary.sort_values(by='Missing Value Count',ascending=False)
missing_value_summary

                     Missing Value Count  Missing Value Percentage
Customer_Name                        162                     0.810
Profit                               127                     0.635
Unit_Price                           126                     0.630
Age                                  125                     0.625
State                                110                     0.550
Quantity                             108                     0.540
Discount_Percentage                  107                     0.535
Payment_Method                       106                     0.530
Product                              106                     0.530
Sales                                105                     0.525
Order_Status                         105                     0.525
Category                             105                     0.525
Gender                               104                     0.520
City                                 104                     0.520
Order_Date                             0                     0.000
Customer_ID                            0                     0.000
Order_ID                               0                     0.000

# DATA CLEANING

## Handling The Missing Values In the Categorical Column

In [46]:
#  1st i have to find the category columns.
df.select_dtypes(include='object').columns

Index(['Order_ID', 'Customer_ID', 'Customer_Name', 'Gender', 'Product',
       'Category', 'Payment_Method', 'City', 'State', 'Order_Status'],
      dtype='object')

### Check Product–Category relationship

In [47]:
df.groupby('Category')['Product'].value_counts()

Category   Product
 Bags      Power Bank     6
           Smart Watch    4
           Webcam         4
           Keyboard       3
           Monitor        3
                         ..
furniture  Printer        1
           SSD            1
           Smartphone     1
           USB Cable      1
           Webcam         1
Name: count, Length: 272, dtype: int64

In [48]:
df.groupby('Product')['Category'].value_counts()

Product   Category
Backpack  Furniture               210
          Networking              190
          Computer Accessories    181
          Electronics             176
          Bags                    169
                                 ...
Webcam    electronics               2
           Furniture                1
          BAGS                      1
          ELECTRONICS               1
          furniture                 1
Name: count, Length: 272, dtype: int64

In [49]:
# Remove the unwanted spaces from the categorical columns.
categorical_columns=df.select_dtypes(include='object').columns
categorical_columns

Index(['Order_ID', 'Customer_ID', 'Customer_Name', 'Gender', 'Product',
       'Category', 'Payment_Method', 'City', 'State', 'Order_Status'],
      dtype='object')

In [50]:
for col in categorical_columns:
    df[col]=df[col].str.strip()

In [51]:
# cross check the values in the columns
df['Category'].unique()  # Here we can see the values in the category column only for the cross check.

array(['Networking', 'Furniture', 'Computer Accessories', 'Electronics',
       'Bags', 'FURNITURE', 'furniture', 'ELECTRONICS',
       'COMPUTER ACCESSORIES', nan, 'bags', 'electronics',
       'computer accessories', 'BAGS'], dtype=object)

In [52]:
# Standardize the values in the category.
df['Category']=df['Category'].str.title()
df['Category'].unique()

array(['Networking', 'Furniture', 'Computer Accessories', 'Electronics',
       'Bags', nan], dtype=object)

In [53]:
# similarly for the Product column
df['Product']=df['Product'].str.title()
df['Product'].unique()

array(['Keyboard', 'Printer', 'Monitor', 'Ssd', 'Smartphone', 'Mouse',
       'Camera', 'Gaming Chair', 'Headphones', 'Bluetooth Speaker',
       'Webcam', 'Smart Watch', 'Usb Cable', 'Backpack', 'Tablet',
       'Power Bank', 'Router', 'External Hard Drive', 'Earbuds', 'Laptop',
       nan], dtype=object)

In [54]:
df['Product']=df['Product'].replace({
    'Ssd':'SSD',
    'Usb Cable':'USB Cable'
})
df['Product'].unique()

array(['Keyboard', 'Printer', 'Monitor', 'SSD', 'Smartphone', 'Mouse',
       'Camera', 'Gaming Chair', 'Headphones', 'Bluetooth Speaker',
       'Webcam', 'Smart Watch', 'USB Cable', 'Backpack', 'Tablet',
       'Power Bank', 'Router', 'External Hard Drive', 'Earbuds', 'Laptop',
       nan], dtype=object)

In [55]:
df['Gender'].unique() #From the op we can say that the gender column is alredy standardized.

array(['Female', 'Male', nan], dtype=object)

In [56]:
df['Payment_Method'].unique() #Alredy standardized.

array(['Wallet', 'UPI', 'Credit Card', 'Cash on Delivery', 'Debit Card',
       'Net Banking', nan], dtype=object)

In [57]:
df['City'].unique()

array(['Kolkata', 'Bangalore', 'Delhi', 'Chennai', 'Mumbai',
       'Bhubaneswar', 'Pune', 'Cuttack', 'Visakhapatnam', 'Ahmedabad',
       'Lucknow', 'Bhopal', 'Jaipur', 'Patna', 'Hyderabad', 'MUMBAI',
       'BANGALORE', nan, 'hyderabad', 'mumbai', 'DELHI', 'delhi', 'PUNE',
       'pune', 'HYDERABAD', 'bangalore'], dtype=object)

In [58]:
# We need to standardize the city column vlues.
df['City']=df['City'].str.title()
df["City"].unique()

array(['Kolkata', 'Bangalore', 'Delhi', 'Chennai', 'Mumbai',
       'Bhubaneswar', 'Pune', 'Cuttack', 'Visakhapatnam', 'Ahmedabad',
       'Lucknow', 'Bhopal', 'Jaipur', 'Patna', 'Hyderabad', nan],
      dtype=object)

In [59]:
df['State'].unique()

array(['West Bengal', 'Karnataka', 'Delhi', 'Tamil Nadu', 'Maharashtra',
       'Odisha', 'Andhra Pradesh', 'Gujarat', 'Uttar Pradesh',
       'Madhya Pradesh', 'Rajasthan', 'Bihar', 'Telangana', nan],
      dtype=object)

In [60]:
df['Order_Status'].unique()

array(['Delivered', 'Returned', nan, 'Pending', 'Cancelled'], dtype=object)

In [61]:
df['Customer_Name'].unique()

array(['Priya Jain', 'Ankit Dutta', nan, 'Sanjay Mohanty',
       'Rohit Pradhan', 'Priya Mohanty', 'Suresh Mehta', 'Arjun Mishra',
       'Rahul Mohanty', 'Amit Rao', 'Manish Singh', 'Manish Mohanty',
       'Rahul Panda', 'Riya Behera', 'Riya Das', 'Pooja Rao',
       'Vivek Mohanty', 'Nisha Kumar', 'Rahul Das', 'Suresh Das',
       'Ankit Yadav', 'Priya Singh', 'Akash Gupta', 'Vikas Pradhan',
       'Karan Rao', 'Priya Das', 'Ankit Sahu', 'Priya Mishra',
       'Kavita Gupta', 'Riya Verma', 'Rohit Kumar', 'Shreya Dutta',
       'Suresh Sahu', 'Vikas Mehta', 'Suresh Rao', 'Abhishek Mehta',
       'Neha Yadav', 'Vivek Panda', 'Anjali Jain', 'Swati Pradhan',
       'Arjun Pradhan', 'Pooja Sharma', 'Swati Verma', 'Manish Mishra',
       'Deepak Panda', 'Suresh Patel', 'Pooja Mishra', 'Arjun Das',
       'Vivek Pradhan', 'Swati Dutta', 'Shreya Jain', 'Neha Mehta',
       'Raj Das', 'Sanjay Rao', 'Shreya Mishra', 'Deepak Gupta',
       'Shreya Verma', 'Sanjay Jain', 'Swati Rao', 'Vikas Nayak',
       'Deepak Sharma', 'Riya Panda', 'Pooja Jain', 'Anjali Patel',
       'Ankit Mishra', 'Ankit Rao', 'Amit Mehta', 'Suresh Gupta',
       'Manish Verma', 'Ankit Nayak', 'Pooja Dutta', 'Pooja Verma',
       'Vivek Yadav', 'Arjun Sharma', 'Kavita Mishra', 'Kavita Singh',
       'Amit Behera', 'Arjun Nayak', 'Raj Verma', 'Priya Rao',
       'Kavita Yadav', 'Deepak Behera', 'Riya Mehta', 'Anjali Singh',
       'Karan Gupta', 'Raj Kumar', 'Karan Mishra', 'Raj Mishra',
       'Shreya Yadav', 'Karan Patel', 'Akash Verma', 'Deepak Kumar',
       'Sneha Pradhan', 'Neha Behera', 'Vivek Mehta', 'Priya Panda',
       'Vikas Rao', 'Ankit Verma', 'Suresh Singh', 'Vikas Singh',
       'Sneha Jain', 'Abhishek Verma', 'Anjali Pradhan', 'Rahul Mishra',
       'Sneha Rao', 'Amit Mishra', 'Shreya Reddy', 'Arjun Singh',
       'Vivek Patel', 'Shreya Panda', 'Arjun Yadav', 'Arjun Mehta',
       'Shreya Nayak', 'Priya Dutta', 'Pooja Pradhan', 'Anjali Nayak',
       'Suresh Reddy', 'Swati Yadav', 'Nisha Nayak', 'Abhishek Singh',
       'Anjali Mohanty', 'Rohit Patel', 'Deepak Rao', 'Nisha Reddy',
       'Deepak Jain', 'Arjun Reddy', 'Sneha Sharma', 'Vivek Jain',
       'Deepak Yadav', 'Sanjay Pradhan', 'Riya Dutta', 'Ankit Jain',
       'Sanjay Nayak', 'Rahul Mehta', 'Suresh Jain', 'Manish Jain',
       'Kavita Mohanty', 'Nisha Behera', 'Abhishek Panda', 'Raj Pradhan',
       'Kavita Dutta', 'Rohit Gupta', 'Rohit Jain', 'Sanjay Mehta',
       'Karan Das', 'Deepak Mishra', 'Riya Pradhan', 'Abhishek Sharma',
       'Karan Nayak', 'Swati Reddy', 'Sneha Yadav', 'Nisha Verma',
       'Amit Kumar', 'Anjali Reddy', 'Kavita Jain', 'Rahul Reddy',
       'Raj Singh', 'Arjun Kumar', 'Amit Sharma', 'Ankit Mehta',
       'Raj Mehta', 'Arjun Jain', 'Shreya Sharma', 'Akash Dutta',
       'Pooja Das', 'Vikas Das', 'Swati Mishra', 'Rahul Kumar',
       'Kavita Verma', 'Sanjay Mishra', 'Manish Pradhan',
       'Abhishek Dutta', 'Riya Jain', 'Raj Yadav', 'Amit Panda',
       'Sneha Reddy', 'Vikas Sahu', 'Manish Yadav', 'Swati Panda',
       'Priya Nayak', 'Vikas Mishra', 'Raj Dutta', 'Karan Reddy',
       'Shreya Mohanty', 'Abhishek Das', 'Sneha Verma', 'Pooja Mohanty',
       'Vikas Panda', 'Riya Nayak', 'Neha Rao', 'Rohit Singh',
       'Vivek Dutta', 'Arjun Verma', 'Sanjay Verma', 'Neha Jain',
       'Sneha Patel', 'Rohit Mohanty', 'Akash Nayak', 'Suresh Verma',
       'Manish Patel', 'Riya Singh', 'Manish Dutta', 'Akash Yadav',
       'Raj Panda', 'Nisha Sharma', 'Nisha Gupta', 'Karan Jain',
       'Vivek Sharma', 'Kavita Patel', 'Swati Das', 'Amit Mohanty',
       'Ankit Behera', 'Suresh Sharma', 'Sanjay Patel', 'Neha Mishra',
       'Priya Verma', 'Suresh Pradhan', 'Neha Das', 'Kavita Kumar',
       'Anjali Rao', 'Abhishek Pradhan', 'Sneha Singh', 'Amit Reddy',
       'Riya Yadav', 'Sanjay Yadav', 'Shreya Patel', 'Deepak Reddy',
       'Suresh Panda', 'Amit Gupta', 'Pooja Mehta', 'Nisha Das',
       'Nisha Mishra', 'Sneha Mohanty', 'Vikas Kumar', 'Suresh Mohanty',
       'Abhishek Rao', 'Rohit Rao', 'Abhishek Kumar', 'Akash Mohanty',
       'Arjun Behera', 'Sanjay Singh', 'Rahul Sahu', 'Rohit Dutta',
       'Karan Kumar', 'Deepak Mehta', 'Swati Behera', 'Sanjay Sharma',
       'Deepak Dutta', 'Riya Mohanty', 'Raj Nayak', 'Akash Patel',
       'Sneha Mehta', 'Karan Verma', 'Sanjay Das', 'Rohit Reddy',
       'Akash Rao', 'Rohit Mehta', 'Vivek Mishra', 'Raj Mohanty',
       'Rahul Verma', 'Raj Rao', 'Sneha Mishra', 'Kavita Rao',
       'Raj Patel', 'Sneha Das', 'Karan Singh', 'Anjali Dutta',
       'Vikas Yadav', 'Deepak Pradhan', 'Sneha Kumar', 'Vikas Behera',
       'Abhishek Mishra', 'Karan Sahu', 'Ankit Mohanty', 'Kavita Behera',
       'Akash Sahu', 'Vikas Reddy', 'Swati Singh', 'Anjali Sharma',
       'Vikas Dutta', 'Swati Sahu', 'Vikas Verma', 'Pooja Behera',
       'Akash Panda', 'Manish Sharma', 'Ankit Pradhan', 'Anjali Das',
       'Anjali Verma', 'Deepak Das', 'Suresh Behera', 'Neha Kumar',
       'Ankit Sharma', 'Suresh Mishra', 'Manish Behera', 'Pooja Panda',
       'Manish Nayak', 'Sanjay Reddy', 'Ankit Singh', 'Priya Yadav',
       'Akash Behera', 'Rohit Das', 'Riya Reddy', 'Riya Gupta',
       'Vikas Mohanty', 'Anjali Gupta', 'Vivek Rao', 'Amit Nayak',
       'Vikas Gupta', 'Amit Jain', 'Rahul Pradhan', 'Nisha Panda',
       'Nisha Pradhan', 'Manish Kumar', 'Raj Gupta', 'Arjun Patel',
       'Sanjay Behera', 'Priya Patel', 'Akash Jain', 'Abhishek Yadav',
       'Suresh Dutta', 'Rahul Singh', 'Sanjay Gupta', 'Rahul Rao',
       'Pooja Singh', 'Nisha Rao', 'Neha Verma', 'Nisha Yadav',
       'Amit Verma', 'Sneha Dutta', 'Arjun Sahu', 'Sneha Nayak',
       'Pooja Sahu', 'Rahul Behera', 'Priya Mehta', 'Swati Mehta',
       'Pooja Kumar', 'Ankit Panda', 'Amit Pradhan', 'Deepak Verma',
       'Shreya Rao', 'Kavita Reddy', 'Vivek Das', 'Vivek Gupta',
       'Suresh Kumar', 'Sneha Panda', 'Swati Patel', 'Abhishek Nayak',
       'Neha Sahu', 'Amit Patel', 'Manish Reddy', 'Neha Reddy',
       'Anjali Behera', 'Amit Yadav', 'Swati Kumar', 'Vivek Reddy',
       'Vivek Behera', 'Shreya Das', 'Ankit Reddy', 'Manish Mehta',
       'Shreya Sahu', 'Priya Reddy', 'Pooja Gupta', 'Sneha Behera',
       'Arjun Mohanty', 'Nisha Mohanty', 'Shreya Kumar', 'Anjali Mishra',
       'Rohit Mishra', 'Neha Patel', 'Vivek Singh', 'Manish Panda',
       'Pooja Nayak', 'Ankit Patel', 'Karan Mohanty', 'Karan Pradhan',
       'Akash Mishra', 'Nisha Patel', 'Nisha Sahu', 'Karan Mehta',
       'Arjun Rao', 'Shreya Singh', 'Sanjay Kumar', 'Manish Rao',
       'Vikas Patel', 'Neha Nayak', 'Riya Sahu', 'Ankit Kumar',
       'Kavita Mehta', 'Akash Das', 'Manish Sahu', 'Swati Mohanty',
       'Sneha Sahu', 'Vivek Nayak', 'Swati Nayak', 'Manish Das',
       'Abhishek Gupta', 'Shreya Behera', 'Vikas Sharma', 'Sanjay Sahu',
       'Vivek Verma', 'Rahul Gupta', 'Manish Gupta', 'Akash Kumar',
       'Akash Singh', 'Ankit Gupta', 'Rahul Patel', 'Rohit Panda',
       'Shreya Mehta', 'Abhishek Reddy', 'Deepak Sahu', 'Akash Mehta',
       'Priya Sahu', 'Pooja Reddy', 'Sanjay Dutta', 'Akash Reddy',
       'Neha Mohanty', 'Anjali Mehta', 'Akash Sharma', 'Kavita Das',
       'Anjali Sahu', 'Rahul Sharma', 'Ankit Das', 'Anjali Kumar',
       'Deepak Singh', 'Swati Gupta', 'Rahul Nayak', 'Kavita Pradhan',
       'Priya Kumar', 'Neha Pradhan', 'Sanjay Panda', 'Kavita Panda',
       'Shreya Pradhan', 'Arjun Dutta', 'Nisha Singh', 'Karan Sharma',
       'Rahul Dutta', 'Rahul Jain', 'Swati Sharma', 'Abhishek Sahu',
       'Priya Gupta', 'Neha Dutta', 'Priya Sharma', 'Amit Singh',
       'Shreya Gupta', 'Pooja Yadav', 'Nisha Jain', 'Raj Jain',
       'Abhishek Behera', 'Sneha Gupta', 'Amit Sahu', 'Karan Dutta',
       'Deepak Patel', 'Raj Sharma', 'Nisha Dutta', 'Kavita Sharma',
       'Neha Singh', 'Priya Behera', 'Rohit Yadav', 'Amit Dutta',
       'Nisha Mehta', 'Raj Sahu', 'Riya Mishra', 'Vikas Jain',
       'Priya Pradhan', 'Swati Jain', 'Rohit Nayak', 'Arjun Gupta',
       'Arjun Panda', 'Suresh Yadav', 'Abhishek Mohanty', 'Riya Rao',
       'Vivek Sahu', 'Rahul Yadav', 'Rohit Sahu', 'Riya Patel',
       'Pooja Patel', 'Deepak Nayak', 'Riya Kumar', 'Neha Sharma',
       'Anjali Panda', 'Neha Panda', 'Anjali Yadav', 'Akash Pradhan',
       'Neha Gupta', 'Kavita Sahu', 'Abhishek Patel', 'Abhishek Jain',
       'Vivek Kumar', 'Raj Reddy', 'Rohit Verma', 'Rohit Sharma',
       'Karan Yadav', 'Amit Das', 'Deepak Mohanty', 'Karan Behera',
       'Rohit Behera', 'Raj Behera', 'Kavita Nayak', 'Suresh Nayak',
       'Riya Sharma', 'Karan Panda'], dtype=object)

## Start Handling Missing Values

In [62]:
# Handle the missing values of the gender column.
df['Gender'].isnull().sum()

np.int64(104)

In [63]:
# Ok there are total 104 missing values in the gender column.
df['Gender']=df['Gender'].fillna(df['Gender'].mode()[0])
# Cross check the Gender Column.
df['Gender'].unique()

array(['Female', 'Male'], dtype=object)

In [64]:
df['Gender'].isnull().sum()

np.int64(0)

In [65]:
df['Payment_Method'].isnull().sum()

np.int64(106)

In [66]:
df['Payment_Method']=df['Payment_Method'].fillna(df["Payment_Method"].mode()[0])
df['Payment_Method'].unique()

array(['Wallet', 'UPI', 'Credit Card', 'Cash on Delivery', 'Debit Card',
       'Net Banking'], dtype=object)

In [67]:
df['Payment_Method'].isnull().sum()

np.int64(0)

In [68]:
df['Order_Status']=df['Order_Status'].fillna(df['Order_Status'].mode()[0])
df['Order_Status'].unique()

array(['Delivered', 'Returned', 'Pending', 'Cancelled'], dtype=object)

In [69]:
df['Order_Status'].isnull().sum()

np.int64(0)

In [70]:
# Now Fill the customer name missing values.
df['Customer_Name']=df['Customer_Name'].fillna("Unknown")
df['Customer_Name'].unique()

array(['Priya Jain', 'Ankit Dutta', 'Unknown', 'Sanjay Mohanty',
       'Rohit Pradhan', 'Priya Mohanty', 'Suresh Mehta', 'Arjun Mishra',
       'Rahul Mohanty', 'Amit Rao', 'Manish Singh', 'Manish Mohanty',
       'Rahul Panda', 'Riya Behera', 'Riya Das', 'Pooja Rao',
       'Vivek Mohanty', 'Nisha Kumar', 'Rahul Das', 'Suresh Das',
       'Ankit Yadav', 'Priya Singh', 'Akash Gupta', 'Vikas Pradhan',
       'Karan Rao', 'Priya Das', 'Ankit Sahu', 'Priya Mishra',
       'Kavita Gupta', 'Riya Verma', 'Rohit Kumar', 'Shreya Dutta',
       'Suresh Sahu', 'Vikas Mehta', 'Suresh Rao', 'Abhishek Mehta',
       'Neha Yadav', 'Vivek Panda', 'Anjali Jain', 'Swati Pradhan',
       'Arjun Pradhan', 'Pooja Sharma', 'Swati Verma', 'Manish Mishra',
       'Deepak Panda', 'Suresh Patel', 'Pooja Mishra', 'Arjun Das',
       'Vivek Pradhan', 'Swati Dutta', 'Shreya Jain', 'Neha Mehta',
       'Raj Das', 'Sanjay Rao', 'Shreya Mishra', 'Deepak Gupta',
       'Shreya Verma', 'Sanjay Jain', 'Swati Rao', 'Vikas Nayak',
       'Deepak Sharma', 'Riya Panda', 'Pooja Jain', 'Anjali Patel',
       'Ankit Mishra', 'Ankit Rao', 'Amit Mehta', 'Suresh Gupta',
       'Manish Verma', 'Ankit Nayak', 'Pooja Dutta', 'Pooja Verma',
       'Vivek Yadav', 'Arjun Sharma', 'Kavita Mishra', 'Kavita Singh',
       'Amit Behera', 'Arjun Nayak', 'Raj Verma', 'Priya Rao',
       'Kavita Yadav', 'Deepak Behera', 'Riya Mehta', 'Anjali Singh',
       'Karan Gupta', 'Raj Kumar', 'Karan Mishra', 'Raj Mishra',
       'Shreya Yadav', 'Karan Patel', 'Akash Verma', 'Deepak Kumar',
       'Sneha Pradhan', 'Neha Behera', 'Vivek Mehta', 'Priya Panda',
       'Vikas Rao', 'Ankit Verma', 'Suresh Singh', 'Vikas Singh',
       'Sneha Jain', 'Abhishek Verma', 'Anjali Pradhan', 'Rahul Mishra',
       'Sneha Rao', 'Amit Mishra', 'Shreya Reddy', 'Arjun Singh',
       'Vivek Patel', 'Shreya Panda', 'Arjun Yadav', 'Arjun Mehta',
       'Shreya Nayak', 'Priya Dutta', 'Pooja Pradhan', 'Anjali Nayak',
       'Suresh Reddy', 'Swati Yadav', 'Nisha Nayak', 'Abhishek Singh',
       'Anjali Mohanty', 'Rohit Patel', 'Deepak Rao', 'Nisha Reddy',
       'Deepak Jain', 'Arjun Reddy', 'Sneha Sharma', 'Vivek Jain',
       'Deepak Yadav', 'Sanjay Pradhan', 'Riya Dutta', 'Ankit Jain',
       'Sanjay Nayak', 'Rahul Mehta', 'Suresh Jain', 'Manish Jain',
       'Kavita Mohanty', 'Nisha Behera', 'Abhishek Panda', 'Raj Pradhan',
       'Kavita Dutta', 'Rohit Gupta', 'Rohit Jain', 'Sanjay Mehta',
       'Karan Das', 'Deepak Mishra', 'Riya Pradhan', 'Abhishek Sharma',
       'Karan Nayak', 'Swati Reddy', 'Sneha Yadav', 'Nisha Verma',
       'Amit Kumar', 'Anjali Reddy', 'Kavita Jain', 'Rahul Reddy',
       'Raj Singh', 'Arjun Kumar', 'Amit Sharma', 'Ankit Mehta',
       'Raj Mehta', 'Arjun Jain', 'Shreya Sharma', 'Akash Dutta',
       'Pooja Das', 'Vikas Das', 'Swati Mishra', 'Rahul Kumar',
       'Kavita Verma', 'Sanjay Mishra', 'Manish Pradhan',
       'Abhishek Dutta', 'Riya Jain', 'Raj Yadav', 'Amit Panda',
       'Sneha Reddy', 'Vikas Sahu', 'Manish Yadav', 'Swati Panda',
       'Priya Nayak', 'Vikas Mishra', 'Raj Dutta', 'Karan Reddy',
       'Shreya Mohanty', 'Abhishek Das', 'Sneha Verma', 'Pooja Mohanty',
       'Vikas Panda', 'Riya Nayak', 'Neha Rao', 'Rohit Singh',
       'Vivek Dutta', 'Arjun Verma', 'Sanjay Verma', 'Neha Jain',
       'Sneha Patel', 'Rohit Mohanty', 'Akash Nayak', 'Suresh Verma',
       'Manish Patel', 'Riya Singh', 'Manish Dutta', 'Akash Yadav',
       'Raj Panda', 'Nisha Sharma', 'Nisha Gupta', 'Karan Jain',
       'Vivek Sharma', 'Kavita Patel', 'Swati Das', 'Amit Mohanty',
       'Ankit Behera', 'Suresh Sharma', 'Sanjay Patel', 'Neha Mishra',
       'Priya Verma', 'Suresh Pradhan', 'Neha Das', 'Kavita Kumar',
       'Anjali Rao', 'Abhishek Pradhan', 'Sneha Singh', 'Amit Reddy',
       'Riya Yadav', 'Sanjay Yadav', 'Shreya Patel', 'Deepak Reddy',
       'Suresh Panda', 'Amit Gupta', 'Pooja Mehta', 'Nisha Das',
       'Nisha Mishra', 'Sneha Mohanty', 'Vikas Kumar', 'Suresh Mohanty',
       'Abhishek Rao', 'Rohit Rao', 'Abhishek Kumar', 'Akash Mohanty',
       'Arjun Behera', 'Sanjay Singh', 'Rahul Sahu', 'Rohit Dutta',
       'Karan Kumar', 'Deepak Mehta', 'Swati Behera', 'Sanjay Sharma',
       'Deepak Dutta', 'Riya Mohanty', 'Raj Nayak', 'Akash Patel',
       'Sneha Mehta', 'Karan Verma', 'Sanjay Das', 'Rohit Reddy',
       'Akash Rao', 'Rohit Mehta', 'Vivek Mishra', 'Raj Mohanty',
       'Rahul Verma', 'Raj Rao', 'Sneha Mishra', 'Kavita Rao',
       'Raj Patel', 'Sneha Das', 'Karan Singh', 'Anjali Dutta',
       'Vikas Yadav', 'Deepak Pradhan', 'Sneha Kumar', 'Vikas Behera',
       'Abhishek Mishra', 'Karan Sahu', 'Ankit Mohanty', 'Kavita Behera',
       'Akash Sahu', 'Vikas Reddy', 'Swati Singh', 'Anjali Sharma',
       'Vikas Dutta', 'Swati Sahu', 'Vikas Verma', 'Pooja Behera',
       'Akash Panda', 'Manish Sharma', 'Ankit Pradhan', 'Anjali Das',
       'Anjali Verma', 'Deepak Das', 'Suresh Behera', 'Neha Kumar',
       'Ankit Sharma', 'Suresh Mishra', 'Manish Behera', 'Pooja Panda',
       'Manish Nayak', 'Sanjay Reddy', 'Ankit Singh', 'Priya Yadav',
       'Akash Behera', 'Rohit Das', 'Riya Reddy', 'Riya Gupta',
       'Vikas Mohanty', 'Anjali Gupta', 'Vivek Rao', 'Amit Nayak',
       'Vikas Gupta', 'Amit Jain', 'Rahul Pradhan', 'Nisha Panda',
       'Nisha Pradhan', 'Manish Kumar', 'Raj Gupta', 'Arjun Patel',
       'Sanjay Behera', 'Priya Patel', 'Akash Jain', 'Abhishek Yadav',
       'Suresh Dutta', 'Rahul Singh', 'Sanjay Gupta', 'Rahul Rao',
       'Pooja Singh', 'Nisha Rao', 'Neha Verma', 'Nisha Yadav',
       'Amit Verma', 'Sneha Dutta', 'Arjun Sahu', 'Sneha Nayak',
       'Pooja Sahu', 'Rahul Behera', 'Priya Mehta', 'Swati Mehta',
       'Pooja Kumar', 'Ankit Panda', 'Amit Pradhan', 'Deepak Verma',
       'Shreya Rao', 'Kavita Reddy', 'Vivek Das', 'Vivek Gupta',
       'Suresh Kumar', 'Sneha Panda', 'Swati Patel', 'Abhishek Nayak',
       'Neha Sahu', 'Amit Patel', 'Manish Reddy', 'Neha Reddy',
       'Anjali Behera', 'Amit Yadav', 'Swati Kumar', 'Vivek Reddy',
       'Vivek Behera', 'Shreya Das', 'Ankit Reddy', 'Manish Mehta',
       'Shreya Sahu', 'Priya Reddy', 'Pooja Gupta', 'Sneha Behera',
       'Arjun Mohanty', 'Nisha Mohanty', 'Shreya Kumar', 'Anjali Mishra',
       'Rohit Mishra', 'Neha Patel', 'Vivek Singh', 'Manish Panda',
       'Pooja Nayak', 'Ankit Patel', 'Karan Mohanty', 'Karan Pradhan',
       'Akash Mishra', 'Nisha Patel', 'Nisha Sahu', 'Karan Mehta',
       'Arjun Rao', 'Shreya Singh', 'Sanjay Kumar', 'Manish Rao',
       'Vikas Patel', 'Neha Nayak', 'Riya Sahu', 'Ankit Kumar',
       'Kavita Mehta', 'Akash Das', 'Manish Sahu', 'Swati Mohanty',
       'Sneha Sahu', 'Vivek Nayak', 'Swati Nayak', 'Manish Das',
       'Abhishek Gupta', 'Shreya Behera', 'Vikas Sharma', 'Sanjay Sahu',
       'Vivek Verma', 'Rahul Gupta', 'Manish Gupta', 'Akash Kumar',
       'Akash Singh', 'Ankit Gupta', 'Rahul Patel', 'Rohit Panda',
       'Shreya Mehta', 'Abhishek Reddy', 'Deepak Sahu', 'Akash Mehta',
       'Priya Sahu', 'Pooja Reddy', 'Sanjay Dutta', 'Akash Reddy',
       'Neha Mohanty', 'Anjali Mehta', 'Akash Sharma', 'Kavita Das',
       'Anjali Sahu', 'Rahul Sharma', 'Ankit Das', 'Anjali Kumar',
       'Deepak Singh', 'Swati Gupta', 'Rahul Nayak', 'Kavita Pradhan',
       'Priya Kumar', 'Neha Pradhan', 'Sanjay Panda', 'Kavita Panda',
       'Shreya Pradhan', 'Arjun Dutta', 'Nisha Singh', 'Karan Sharma',
       'Rahul Dutta', 'Rahul Jain', 'Swati Sharma', 'Abhishek Sahu',
       'Priya Gupta', 'Neha Dutta', 'Priya Sharma', 'Amit Singh',
       'Shreya Gupta', 'Pooja Yadav', 'Nisha Jain', 'Raj Jain',
       'Abhishek Behera', 'Sneha Gupta', 'Amit Sahu', 'Karan Dutta',
       'Deepak Patel', 'Raj Sharma', 'Nisha Dutta', 'Kavita Sharma',
       'Neha Singh', 'Priya Behera', 'Rohit Yadav', 'Amit Dutta',
       'Nisha Mehta', 'Raj Sahu', 'Riya Mishra', 'Vikas Jain',
       'Priya Pradhan', 'Swati Jain', 'Rohit Nayak', 'Arjun Gupta',
       'Arjun Panda', 'Suresh Yadav', 'Abhishek Mohanty', 'Riya Rao',
       'Vivek Sahu', 'Rahul Yadav', 'Rohit Sahu', 'Riya Patel',
       'Pooja Patel', 'Deepak Nayak', 'Riya Kumar', 'Neha Sharma',
       'Anjali Panda', 'Neha Panda', 'Anjali Yadav', 'Akash Pradhan',
       'Neha Gupta', 'Kavita Sahu', 'Abhishek Patel', 'Abhishek Jain',
       'Vivek Kumar', 'Raj Reddy', 'Rohit Verma', 'Rohit Sharma',
       'Karan Yadav', 'Amit Das', 'Deepak Mohanty', 'Karan Behera',
       'Rohit Behera', 'Raj Behera', 'Kavita Nayak', 'Suresh Nayak',
       'Riya Sharma', 'Karan Panda'], dtype=object)

In [71]:
df['Customer_Name'].isnull().sum()

np.int64(0)

In [72]:
# Now Fill the missing values in the Product Column.
df['Product'].isnull().sum()

np.int64(106)

In [73]:
df.shape

(20000, 17)

In [74]:
df.isnull().sum()

Order_ID                 0
Order_Date               0
Customer_ID              0
Customer_Name            0
Gender                   0
Age                    125
Product                106
Category               105
Quantity               108
Unit_Price             126
Discount_Percentage    107
Sales                  105
Profit                 127
Payment_Method           0
City                   104
State                  110
Order_Status             0
dtype: int64

In [75]:
df['Product'].isnull().sum()

np.int64(106)

In [76]:
df[df['Product'].isnull()][['Product','Category']]

      Product     Category
452       NaN    Furniture
717       NaN    Furniture
743       NaN  Electronics
1283      NaN         Bags
1330      NaN    Furniture
...       ...          ...
19166     NaN    Furniture
19690     NaN   Networking
19741     NaN  Electronics
19758     NaN  Electronics
19904     NaN  Electronics

[106 rows x 2 columns]

In [77]:
# find the category wise product counts.
df.groupby('Category')['Product'].value_counts()

Category    Product
Bags        Smart Watch          227
            Bluetooth Speaker    221
            Keyboard             209
            SSD                  207
            Monitor              205
                                ...
Networking  Router               190
            Camera               188
            Mouse                188
            Smartphone           185
            Tablet               184
Name: count, Length: 100, dtype: int64

In [78]:
most_common_product=df.groupby('Category')['Product'].agg(lambda x: x.mode()[0])
most_common_product

Category
Bags                    Smart Watch
Computer Accessories    Smart Watch
Electronics                  Webcam
Furniture                 USB Cable
Networking              Smart Watch
Name: Product, dtype: object

In [79]:
df['Product']=df['Product'].fillna(df['Category'].map(most_common_product))
df['Product'].head(5)

0      Keyboard
1       Printer
2       Monitor
3           SSD
4    Smartphone
Name: Product, dtype: object

In [80]:
df['Product'].isnull().sum()

np.int64(2)

In [81]:
# check the remain 2 recordes 
df[df['Product'].isnull()][["Product",'Category']]

      Product Category
10491     NaN      NaN
11023     NaN      NaN

In [82]:
df['Product']=df['Product'].fillna('Unknown')
df['Product'].isnull().sum()

np.int64(0)

In [83]:
# Fill the missing values in the City column.
df['City'].isnull().sum()

np.int64(104)

In [84]:
# Check the relationship beetween the City and State Column
df[df['City'].isnull()][['City','State']]

      City          State
252    NaN         Odisha
712    NaN      Telangana
783    NaN         Odisha
927    NaN  Uttar Pradesh
1089   NaN         Odisha
...    ...            ...
19523  NaN      Telangana
19552  NaN    Maharashtra
19852  NaN  Uttar Pradesh
19855  NaN      Karnataka
19886  NaN    Maharashtra

[104 rows x 2 columns]

In [85]:
df.groupby('State')['City'].value_counts()

State           City
Andhra Pradesh  Visakhapatnam    1341
                Mumbai              9
                Bangalore           4
                Pune                3
                Hyderabad           1
                                 ...
West Bengal     Delhi               4
                Mumbai              3
                Bangalore           2
                Hyderabad           2
                Pune                2
Name: count, Length: 74, dtype: int64

In [86]:
# Find the most common city
most_common_city=df.groupby('State')['City'].agg(lambda x:x.mode()[0])
most_common_city

State
Andhra Pradesh    Visakhapatnam
Bihar                     Patna
Delhi                     Delhi
Gujarat               Ahmedabad
Karnataka             Bangalore
Madhya Pradesh           Bhopal
Maharashtra                Pune
Odisha              Bhubaneswar
Rajasthan                Jaipur
Tamil Nadu              Chennai
Telangana             Hyderabad
Uttar Pradesh           Lucknow
West Bengal             Kolkata
Name: City, dtype: object

In [87]:
df['City']=df['City'].fillna(df['State'].map(most_common_city))
df['City'].isnull().sum()

np.int64(0)

In [88]:
df['City'].head()

0      Kolkata
1    Bangalore
2        Delhi
3    Bangalore
4      Chennai
Name: City, dtype: object

In [89]:
# Check the missing values in the State column
df['State'].isnull().sum()

np.int64(110)

In [90]:
# Check the relation With the City Column
df[df['State'].isnull()][['State','City']]

      State       City
162     NaN    Lucknow
594     NaN  Ahmedabad
618     NaN      Delhi
713     NaN  Ahmedabad
924     NaN  Bangalore
...     ...        ...
19205   NaN  Ahmedabad
19527   NaN    Cuttack
19528   NaN    Kolkata
19604   NaN     Jaipur
19735   NaN      Delhi

[110 rows x 2 columns]

In [91]:
# Find the most common city of each State
df.groupby('City')['State'].value_counts()

City           State
Ahmedabad      Gujarat           1235
Bangalore      Karnataka         1303
               Bihar               10
               Odisha               9
               Madhya Pradesh       6
                                 ...
Pune           Andhra Pradesh       3
               Delhi                2
               Gujarat              2
               West Bengal          2
Visakhapatnam  Andhra Pradesh    1349
Name: count, Length: 74, dtype: int64

In [92]:
# Select the heighest frequency one State
most_common_state=df.groupby('City')['State'].agg(lambda x:x.mode()[0])
most_common_state

City
Ahmedabad               Gujarat
Bangalore             Karnataka
Bhopal           Madhya Pradesh
Bhubaneswar              Odisha
Chennai              Tamil Nadu
Cuttack                  Odisha
Delhi                     Delhi
Hyderabad             Telangana
Jaipur                Rajasthan
Kolkata             West Bengal
Lucknow           Uttar Pradesh
Mumbai              Maharashtra
Patna                     Bihar
Pune                Maharashtra
Visakhapatnam    Andhra Pradesh
Name: State, dtype: object

In [93]:
# Fill the misssing vlues in the state column
df['State']=df['State'].fillna(df['City'].map(most_common_state))
df['State'].isnull().sum()

np.int64(0)

In [94]:
# Fill the missing values in the Category  column
df['Category'].isnull().sum()

np.int64(105)

In [95]:
# Check the relation with the product column
df[df['Category'].isnull()][['Category','City']]

      Category           City
128        NaN         Jaipur
709        NaN        Lucknow
1150       NaN      Ahmedabad
1219       NaN           Pune
1252       NaN      Ahmedabad
...        ...            ...
19135      NaN  Visakhapatnam
19246      NaN         Mumbai
19453      NaN          Patna
19780      NaN      Ahmedabad
19855      NaN      Bangalore

[105 rows x 2 columns]

In [96]:
# Find the number of Frequency of the category by product wise.
df.groupby('Product')['Category'].value_counts()  # By default sort in ascending order.

Product   Category
Backpack  Furniture               214
          Networking              190
          Computer Accessories    186
          Electronics             178
          Bags                    170
                                 ...
Webcam    Electronics             242
          Furniture               224
          Bags                    200
          Networking              198
          Computer Accessories    184
Name: count, Length: 100, dtype: int64

In [97]:
# Select the heighest frequency one.
most_common_category=df.groupby('Product')['Category'].agg(lambda x:x.mode())
most_common_category

Product
Backpack                          Furniture
Bluetooth Speaker                      Bags
Camera                                 Bags
Earbuds                          Networking
External Hard Drive               Furniture
Gaming Chair                      Furniture
Headphones                      Electronics
Keyboard                          Furniture
Laptop                 Computer Accessories
Monitor                          Networking
Mouse                  Computer Accessories
Power Bank                      Electronics
Printer                  [Bags, Networking]
Router                          Electronics
SSD                    Computer Accessories
Smart Watch                            Bags
Smartphone                      Electronics
Tablet                            Furniture
USB Cable                         Furniture
Unknown                                  []
Webcam                          Electronics
Name: Category, dtype: object

In [98]:
# Fill the missing value in the column called category
df['Category']=df['Category'].fillna(df['Product'].map(most_common_category))
df['Category'].isnull().sum()

np.int64(0)

In [99]:
df['Order_Status'].isnull().sum()

np.int64(0)

## Handle The Missing Value In the Numerical columns

In [100]:
numerical_columns=df.select_dtypes(include='number').columns
numerical_columns

Index(['Age', 'Quantity', 'Unit_Price', 'Discount_Percentage', 'Sales',
       'Profit'],
      dtype='object')

In [101]:
df[numerical_columns].isnull().sum()

Age                    125
Quantity               108
Unit_Price             126
Discount_Percentage    107
Sales                  105
Profit                 127
dtype: int64

In [102]:
# Calculate the missing percentage
missing_percentage=(df[numerical_columns].isnull().sum()/len(df))*100
missing_percentage

Age                    0.625
Quantity               0.540
Unit_Price             0.630
Discount_Percentage    0.535
Sales                  0.525
Profit                 0.635
dtype: float64

In [103]:
# sort the missing percentage
missing_num=missing_percentage.sort_values(ascending=False)
missing_num

Profit                 0.635
Unit_Price             0.630
Age                    0.625
Quantity               0.540
Discount_Percentage    0.535
Sales                  0.525
dtype: float64

In [104]:
# Check the missing values in the age column
df['Age'].isnull().sum()

np.int64(125)

## Checking For the outliers

In [105]:
Q1=df['Age'].quantile(0.25)
Q3=df['Age'].quantile(0.75)
IQR=Q3-Q1
lower=Q1-(1.5*IQR)
upper=Q3+(1.5*IQR)
print('Lower=',lower)
print('Upper',upper)

Lower= -6.0
Upper 90.0

In [106]:
# Find the outliers
df[(df['Age']<lower)|(df['Age']>upper)].head()

Empty DataFrame
Columns: [Order_ID, Order_Date, Customer_ID, Customer_Name, Gender, Age, Product, Category, Quantity, Unit_Price, Discount_Percentage, Sales, Profit, Payment_Method, City, State, Order_Status]
Index: []

In [107]:
df['Age'].describe()

count    19875.000000
mean        41.600050
std         13.874268
min         18.000000
25%         30.000000
50%         41.000000
75%         54.000000
max         65.000000
Name: Age, dtype: float64

#### Science we don't found any outliers in the Age so we fill the missing values by mean()

In [108]:
df['Age']=df['Age'].fillna(df['Age'].mean())
df['Age'].isnull().sum()

np.int64(0)

In [109]:
# check the missing values in the Quantity column
df['Quantity'].isnull().sum()

np.int64(108)

In [110]:
df['Quantity'].describe()

count    19892.000000
mean         3.471144
std         14.425984
min         -5.000000
25%          2.000000
50%          3.000000
75%          4.000000
max        500.000000
Name: Quantity, dtype: float64

### Checking For the outliers in the quantity column

In [111]:
Q1=df['Quantity'].quantile(0.25)
Q3=df['Quantity'].quantile(0.75)
IQR=Q3-Q1
lower=Q1-(1.5*IQR)
upper=Q3+(1.5*IQR)
print('Lower=',lower)
print('Upper=',upper)

Lower= -1.0
Upper= 7.0

In [112]:
# Find the outliers
outliers=df[(df['Quantity']<lower)|(df['Quantity']>upper)]
outliers.head()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Gender,Age,Product,Category,Quantity,Unit_Price,Discount_Percentage,Sales,Profit,Payment_Method,City,State,Order_Status
325,ORD113652,2025-10-25,CUST23652,Abhishek Rao,Female,34.0,Bluetooth Speaker,Furniture,500.0,85659.0,5.0,325504.20,61100.02,Credit Card,Visakhapatnam,Andhra Pradesh,Returned
1030,ORD108021,2025-03-30,CUST18021,Rohit Patel,Female,57.0,Smart Watch,Furniture,100.0,35625.0,25.0,133593.75,23115.60,UPI,Patna,Bihar,Cancelled
2040,ORD112786,2024-06-10,CUST22786,Nisha Mishra,Female,37.0,Router,Networking,500.0,4894.0,10.0,4404.60,1074.29,Debit Card,Delhi,Delhi,Returned
2125,ORD115484,2022-11-02,CUST25484,Riya Pradhan,Male,41.0,Gaming Chair,Bags,-5.0,55428.0,15.0,94227.60,11857.32,Cash on Delivery,Bhubaneswar,Odisha,Delivered
2247,ORD106194,2023-01-18,CUST16194,Manish Das,Female,60.0,Smartphone,Computer Accessories,100.0,99167.0,10.0,89250.30,9700.28,Debit Card,Pune,Maharashtra,Delivered

In [113]:
outliers['Quantity'].sort_values()

19329     -5.0
16463     -5.0
9555      -5.0
8118      -5.0
7947      -5.0
9806      -5.0
18422     -5.0
6296      -5.0
5993      -5.0
5424      -5.0
5240      -5.0
4630      -5.0
9174      -5.0
4436      -5.0
3821      -5.0
10467     -5.0
3432      -5.0
12532     -5.0
13278     -5.0
2125      -5.0
13849     -5.0
14076     -5.0
4431      -5.0
18171     -5.0
10981    100.0
16120    100.0
15519    100.0
12285    100.0
14406    100.0
8875     100.0
14098    100.0
5811     100.0
3756     100.0
3654     100.0
3587     100.0
19005    100.0
2247     100.0
19252    100.0
1030     100.0
9162     100.0
16024    500.0
18498    500.0
18414    500.0
325      500.0
11886    500.0
10500    500.0
10088    500.0
9302     500.0
19283    500.0
7363     500.0
6591     500.0
2468     500.0
2308     500.0
2040     500.0
14979    500.0
9252     500.0
Name: Quantity, dtype: float64

In [114]:
non_outliers=df.loc[(df['Quantity']>lower)&(df['Quantity']<upper),'Quantity']
non_outliers

0        5.0
1        2.0
2        1.0
3        5.0
4        5.0
        ...
19995    2.0
19996    5.0
19997    2.0
19998    5.0
19999    1.0
Name: Quantity, Length: 19817, dtype: float64

In [115]:
# Fill the missing values in the Quantity column
df['Quantity']=df['Quantity'].fillna(non_outliers.median())
df['Quantity'].isnull().sum()

np.int64(0)

In [116]:
# Check the mising values in the Unit_Price column
df['Unit_Price'].isnull().sum()

np.int64(126)

In [117]:
df['Unit_Price'].describe()

count    19874.000000
mean     50133.168562
std      28777.947200
min        501.000000
25%      24924.500000
50%      50299.500000
75%      75111.000000
max      99998.000000
Name: Unit_Price, dtype: float64

### Check The outliers for the Unit_Price column

In [118]:
Q1=df['Unit_Price'].quantile(0.25)
Q3=df['Unit_Price'].quantile(0.75)
IQR=Q3-Q1
lower=Q1-(1.5*IQR)
upper=Q3+(1.5*IQR)
print('Lower=',lower)
print('Upper=',upper)

Lower= -50355.25
Upper= 150390.75

In [119]:
# Find The Outliers are
df[(df['Unit_Price']<lower)|(df['Unit_Price']>upper)]

Empty DataFrame
Columns: [Order_ID, Order_Date, Customer_ID, Customer_Name, Gender, Age, Product, Category, Quantity, Unit_Price, Discount_Percentage, Sales, Profit, Payment_Method, City, State, Order_Status]
Index: []

### Science There are no outliers in the unit_price column and the mean and median are almost same so we fill the value by mean

In [120]:
df['Unit_Price']=df['Unit_Price'].fillna(df['Unit_Price'].mean())
df['Unit_Price'].isnull().sum()

np.int64(0)

In [121]:
# find the missing values in the Discount Percentage
df['Discount_Percentage'].isnull().sum()

np.int64(107)

In [122]:
df['Discount_Percentage'].describe()

count    19893.000000
mean        15.185492
std         11.558752
min        -10.000000
25%          5.000000
50%         15.000000
75%         25.000000
max        150.000000
Name: Discount_Percentage, dtype: float64

In [123]:
Q1=df['Discount_Percentage'].quantile(0.25)
Q3=df['Discount_Percentage'].quantile(0.75)
IQR=Q3-Q1
lower=Q1-(1.5*IQR)
upper=Q3+(1.5*IQR)
print('Lower=',lower)
print('Upper=',upper)

Lower= -25.0
Upper= 55.0

In [124]:
# find the outliers
df[(df['Discount_Percentage']<lower)|(df['Discount_Percentage']>upper)].head()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Gender,Age,Product,Category,Quantity,Unit_Price,Discount_Percentage,Sales,Profit,Payment_Method,City,State,Order_Status
329,ORD103753,2025-08-03,CUST13753,Akash Mohanty,Female,39.0,Headphones,Furniture,4.0,98759.0,150.0,355532.4,43927.89,UPI,Bhubaneswar,Odisha,Pending
1169,ORD105762,2024-04-19,CUST15762,Kavita Singh,Female,34.0,External Hard Drive,Furniture,3.0,30040.0,105.0,63084.0,6821.40,UPI,Kolkata,West Bengal,Returned
1819,ORD101706,2025-02-21,CUST11706,Raj Reddy,Female,55.0,Laptop,Electronics,4.0,21783.0,150.0,78418.8,12900.92,Net Banking,Cuttack,Odisha,Delivered
2376,ORD103965,2022-08-22,CUST13965,Sneha Pradhan,Female,65.0,Printer,Furniture,1.0,64001.0,150.0,44800.7,3179.06,Net Banking,Ahmedabad,Gujarat,Delivered
2628,ORD114056,2024-01-04,CUST24056,Ankit Sharma,Male,23.0,Bluetooth Speaker,Furniture,4.0,79146.0,150.0,253267.2,15420.47,Debit Card,Pune,Maharashtra,Returned

### So we have two different problems i.Statistical outlier: 150  ii.Invalid business value: negative discounts such as -10

In [125]:
df[(df['Discount_Percentage']<lower)|(df['Discount_Percentage']>upper)][['Discount_Percentage']]

       Discount_Percentage
329                  150.0
1169                 105.0
1819                 150.0
2376                 150.0
2628                 150.0
2770                 150.0
2976                 150.0
3092                 150.0
3660                 150.0
3756                 150.0
3975                 150.0
4355                 105.0
5396                 150.0
5436                 105.0
5930                 105.0
6432                 150.0
6991                 150.0
7759                 150.0
7816                 150.0
8207                 105.0
8907                 150.0
9352                 105.0
9578                 105.0
9879                 150.0
9937                 105.0
10474                150.0
10830                150.0
10871                105.0
10921                150.0
11100                105.0
12597                105.0
12632                150.0
13030                150.0
13525                105.0
14485                150.0
14570                105.0
15167                150.0
17090                150.0
18789                150.0
19007                105.0
19578                150.0
19640                150.0
19953                105.0
19967                105.0

In [126]:
df[df['Discount_Percentage'] < 0][['Discount_Percentage']]

       Discount_Percentage
41                    -5.0
113                  -10.0
202                  -10.0
250                  -10.0
388                   -5.0
...                    ...
17803                 -5.0
18121                 -5.0
18141                 -5.0
18142                -10.0
19068                 -5.0

[64 rows x 1 columns]

In [127]:
valid_discount=df.loc[(df['Discount_Percentage']>=0)&(df['Discount_Percentage']<upper),'Discount_Percentage']
valid_discount

0        10.0
1         0.0
2        20.0
3        25.0
4        15.0
         ...
19995    15.0
19996    20.0
19997    30.0
19998    10.0
19999    10.0
Name: Discount_Percentage, Length: 19785, dtype: float64

In [128]:
# fill the missing valu in the Discount Percentage column
df['Discount_Percentage']=df['Discount_Percentage'].fillna(valid_discount.median())
df['Discount_Percentage'].isnull().sum()

np.int64(0)

In [129]:
# find the missing values in the Sales Column
df['Sales'].isnull().sum()

np.int64(105)

In [130]:
df['Sales'].describe()

count      19895.000000
mean      128860.331345
std       105620.721515
min        -1000.000000
25%        46112.500000
50%        98467.200000
75%       189966.700000
max      1000000.000000
Name: Sales, dtype: float64

In [131]:
Q1=df['Sales'].quantile(0.25)
Q3=df['Sales'].quantile(0.75)
IQR=Q3-Q1
lower=Q1-(1.5*IQR)
upper=Q3+(1.5*IQR)
print('Lower=',lower)
print('Upper=',upper)

Lower= -169668.80000000002
Upper= 405748.0

In [132]:
df[(df['Sales']<lower)|(df['Sales']>upper)].head()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Gender,Age,Product,Category,Quantity,Unit_Price,Discount_Percentage,Sales,Profit,Payment_Method,City,State,Order_Status
5,ORD111964,2022-01-06,CUST21964,Priya Mohanty,Female,43.0,Mouse,Networking,5.0,95516.0,15.0,405943.00,84387.61,Wallet,Mumbai,Maharashtra,Delivered
9,ORD108116,2022-06-02,CUST18116,Amit Rao,Male,51.0,Gaming Chair,Electronics,5.0,93139.0,0.0,465695.00,95292.14,Debit Card,Pune,Maharashtra,Returned
21,ORD107460,2023-05-20,CUST17460,Ankit Yadav,Male,31.0,USB Cable,Networking,5.0,92937.0,5.0,441450.75,64683.91,Cash on Delivery,Mumbai,Maharashtra,Delivered
53,ORD113420,2024-02-08,CUST23420,Swati Dutta,Male,26.0,Gaming Chair,Bags,5.0,98073.0,5.0,465846.75,77835.84,Wallet,Delhi,Delhi,Cancelled
62,ORD117060,2022-06-29,CUST27060,Deepak Gupta,Male,54.0,Keyboard,Electronics,5.0,96595.0,10.0,434677.50,39358.92,UPI,Visakhapatnam,Andhra Pradesh,Delivered

In [133]:
df[df['Sales']<0][['Sales']]

        Sales
368   -1000.0
1825   -500.0
2134   -500.0
2235  -1000.0
2273  -1000.0
3154  -1000.0
3578   -500.0
4844  -1000.0
6295  -1000.0
6427  -1000.0
6608  -1000.0
7807  -1000.0
7827  -1000.0
8569   -500.0
9393  -1000.0
10626 -1000.0
12209  -500.0
12340 -1000.0
12638 -1000.0
14053  -500.0
14622 -1000.0
14646  -500.0
15433  -500.0
16689 -1000.0
17176  -500.0
17484 -1000.0
18286 -1000.0
18940 -1000.0

In [134]:
valid_sales=df.loc[(df['Sales']>=0)&(df['Sales']<upper),'Sales']
valid_sales

0        132205.50
1        135556.00
2         10929.60
3        124631.25
4         37667.75
           ...
19995    136787.10
19996    125268.00
19997     19080.60
19998     33952.50
19999     69837.30
Name: Sales, Length: 19560, dtype: float64

In [135]:
# fill the missing values in the sales column
df['Sales']=df['Sales'].fillna(valid_sales.median())
df['Sales'].isnull().sum()

np.int64(0)

In [136]:
df.select_dtypes(include='number').isnull().sum()

Age                      0
Quantity                 0
Unit_Price               0
Discount_Percentage      0
Sales                    0
Profit                 127
dtype: int64

In [137]:
df.select_dtypes(include='object').isnull().sum()

Order_ID          0
Customer_ID       0
Customer_Name     0
Gender            0
Product           0
Category          0
Payment_Method    0
City              0
State             0
Order_Status      0
dtype: int64

In [138]:
# find the missing values in the profit colimn
df['Profit'].isnull().sum()

np.int64(127)

In [139]:
df['Profit'].describe()

count     19873.000000
mean      19270.322241
std       18100.583470
min          35.270000
25%        5855.920000
50%       13554.670000
75%       27202.200000
max      117234.610000
Name: Profit, dtype: float64

In [140]:
Q1=df['Profit'].quantile(0.25)
Q3=df['Profit'].quantile(0.75)
IQR=Q3-Q1
lower=Q1-(1.5*IQR)
upper=Q3+(1.5*IQR)
print('Lower=',lower)
print('Upper=',upper)

Lower= -26163.5
Upper= 59221.619999999995

In [141]:
df[(df['Profit'] < lower) | (df['Profit'] > upper)][['Profit']]

         Profit
5      84387.61
9      95292.14
21     64683.91
40     65816.23
43     71281.50
...         ...
19880  83471.04
19882  65183.27
19896  74648.19
19903  91584.23
19919  64407.69

[862 rows x 1 columns]

In [142]:
valid_profit = df.loc[
    (df['Profit'] >= lower) & (df['Profit'] <= upper),
    'Profit'
]

In [143]:
df['Profit'] = df['Profit'].fillna(valid_profit.median())
df['Profit'].isnull().sum()

np.int64(0)

In [144]:
df.isnull().sum()

Order_ID               0
Order_Date             0
Customer_ID            0
Customer_Name          0
Gender                 0
Age                    0
Product                0
Category               0
Quantity               0
Unit_Price             0
Discount_Percentage    0
Sales                  0
Profit                 0
Payment_Method         0
City                   0
State                  0
Order_Status           0
dtype: int64

## Handle The Invalid values In the columns

In [145]:
df['Quantity'].value_counts().sort_index()

Quantity
-5.0        24
-1.0        19
 0.0        29
 1.0      3824
 2.0      4038
 3.0      4065
 4.0      4029
 5.0      3940
 100.0      16
 500.0      16
Name: count, dtype: int64

In [147]:
df["Quantity"].isnull().sum()

np.int64(0)

In [148]:
df.loc[(df['Quantity']<1)|(df['Quantity']>5),'Quantity']=np.nan

In [149]:
df['Quantity'].isnull().sum()

np.int64(104)

In [150]:
# Fill the values
valid_quantity=df.loc[(df['Quantity']>=1)&(df['Quantity']<=5),'Quantity']
df['Quantity']=df['Quantity'].fillna(valid_quantity.median())
df['Quantity'].isnull().sum()

np.int64(0)

In [152]:
df['Quantity'].value_counts()

Quantity
3.0    4169
2.0    4038
4.0    4029
5.0    3940
1.0    3824
Name: count, dtype: int64

In [153]:
# Handle the Invalid Values in the Discount_Percentage column
df['Discount_Percentage'].value_counts(dropna=False).sort_index()

Discount_Percentage
-10.0       36
-5.0        28
 0.0      2834
 5.0      2876
 10.0     2789
 15.0     2844
 20.0     2870
 25.0     2878
 30.0     2801
 105.0      16
 150.0      28
Name: count, dtype: int64

In [156]:
df.loc[(df['Discount_Percentage']<0)|(df['Discount_Percentage']>100),'Discount_Percentage']=np.nan
valid_values=df.loc[(df['Discount_Percentage']>=0)&(df['Discount_Percentage']<=100),'Quantity']
# fill the Invalid values
df['Discount_Percentage']=df['Discount_Percentage'].fillna(valid_values.median())

In [157]:
# cross check the Discount Percentage column
df['Discount_Percentage'].isnull().sum()

np.int64(0)

In [159]:
df['Discount_Percentage'].value_counts()

Discount_Percentage
25.0    2878
5.0     2876
20.0    2870
15.0    2844
0.0     2834
30.0    2801
10.0    2789
3.0      108
Name: count, dtype: int64